### PR TITLE
delete manifest from docs (replaced by case studies)

### PR DESCRIPTION
**Pull request by jbloom**

### CODE REVIEW

**Review by skhilton — COMMENTED** [review]
I want to talk about this a little bit. I would like to have a list of datasets that use the tool. Do you think that is a bad idea? If not, where do you think it should be hosted?

**Comment by jbloom** [comment]
I think it should be hosted in the sub repos we are making (I am making one for flu right now). We can link to those when we are happy with them.

But I feel like trying to track all datasets hosted by the tool in the docs is not maintainable, because we anticipate people adding the datasets to the other virus-specific repos, not to the docs. If they start being hosted in two places they will become obsolete / out of date.

Plus right now the manifest is broken: go to it and no data displays when you click on either link:
https://dms-view.github.io/docs/manifest/

**Comment by skhilton** [comment]
I would like a way to showcase the diversity of datasets that the tool can use as we get more examples. What you are suggesting is that we build out the case studies (though keeping it to manageable number) if we highlight this?

**Comment by jbloom** [comment]
I think it's just best to have repos for influenza virus etc, and then say: [Go to the list of influenza virus datasets](https://github.com/dms-view/influenza) to see how `dms-view` can be used to visualize datasets for influenza virus.

Then those datasets are hosted and maintained on that website. Otherwise you have to host all the data on `docs` or independently update the links every time someone changes an external dataset. This is essentially putting the examples in two places, and I don't think it makes sense.

**Pull request merged**
